chimera-vfs: convert FileNotFoundHimeraException into StaleException
fixes stacktrace:

org.dcache.chimera.FileNotFoundHimeraFsException: path [00006B81AB5674CD4FABA084919EDE644744] does not exist
        at org.dcache.chimera.JdbcFs.stat(JdbcFs.java:729) ~[chimera-2.12.0-SNAPSHOT.jar:2.12.0-SNAPSHOT]
        at org.dcache.chimera.FsInode.stat(FsInode.java:269) ~[chimera-2.12.0-SNAPSHOT.jar:2.12.0-SNAPSHOT]
        at org.dcache.chimera.FsInode.statCache(FsInode.java:282) ~[chimera-2.12.0-SNAPSHOT.jar:2.12.0-SNAPSHOT]
        at org.dcache.nfs.vfs.ChimeraVfs.getAcl(ChimeraVfs.java:269) ~[nfs4j-core-0.10.0.jar:0.10.0]
        at org.dcache.nfs.vfs.ForwardingFileSystem.getAcl(ForwardingFileSystem.java:136) ~[nfs4j-core-0.10.0.jar:0.10.0]
        at org.dcache.nfs.vfs.PseudoFs.getAcl(PseudoFs.java:299) ~[nfs4j-core-0.10.0.jar:0.10.0]
        at org.dcache.nfs.v4.OperationSETATTR.xdr2fattr(OperationSETATTR.java:155) ~[nfs4j-core-0.10.0.jar:0.10.0]
        at org.dcache.nfs.v4.OperationSETATTR.setAttributes(OperationSETATTR.java:92) ~[nfs4j-core-0.10.0.jar:0.10.0]
        at org.dcache.nfs.v4.OperationOPEN.process(OperationOPEN.java:187) ~[nfs4j-core-0.10.0.jar:0.10.0]
        at org.dcache.nfs.v4.NFSServerV41.NFSPROC4_COMPOUND_4(NFSServerV41.java:144) ~[nfs4j-core-0.10.0.jar:0.10.0]
        at org.dcache.nfs.v4.xdr.nfs4_prot_NFS4_PROGRAM_ServerStub.dispatchOncRpcCall(nfs4_prot_NFS4_PROGRAM_ServerStub.java:48) [nfs4j-core-0.10.0.jar:0.10.0]
        at org.dcache.xdr.RpcDispatcher$1.run(RpcDispatcher.java:85) [oncrpc4j-core-2.3.1.jar:na]
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565) [grizzly-framework-2.3.17.jar:2.3.17]
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545) [grizzly-framework-2.3.17.jar:2.3.17]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_31]

Acked-By: Gerd Behrmann
Acked-By: Paul Millar
Target: master, 0.10, 0.9
Require-notes: yes
Require-book: no